feat: Add config for sqlfmt
stevearc/conform.nvim pull request #145
Opened 2023-10-16 09:16 UTC by ronmorgen1

This PR adds support for [sqlfmt](https://docs.sqlfmt.com)

2023-10-16 14:52 UTC, stevearc requested changes

2023-10-16 14:52 UTC, stevearc commented on lua/conform/formatters/sqlfmt.lua
> +  args = { "$FILENAME" },
From [the docs](https://docs.sqlfmt.com/getting-started/using-sqlfmt), it looks like the correct way to format with stdin/stdout is to pass a single argument: `-`

2024-02-22 11:18 UTC, MattiasMTS commented
Any plan to try and get this merged?

2024-02-22 15:46 UTC, closed without merging

2024-02-22 15:46 UTC, stevearc commented
replaced by #307