add stylish-haskell support
stevearc/conform.nvim pull request #210
Opened 2023-11-20 12:50 UTC by bbarks15

2023-11-20 15:38 UTC, stevearc commented
You linked to the fourmolu formatter, is that intended?

2023-11-20 22:57 UTC, brandonbarkerRAC commented
No that is not intended 😂

Will get that fixed

2023-11-20 23:03 UTC, bbarks15 commented
Was not intended lol

Fixed

2023-11-20 23:34 UTC, stevearc requested changes

2023-11-20 23:34 UTC, stevearc commented on lua/conform/formatters/stylish-haskell.lua
> +  args = { "$FILENAME" },
From the docs, it looks like `stylish-haskell` supports formatting via stdin & stdout. Do you need this arg?

2024-06-01 18:57 UTC, stevearc commented
Implemented in #435

2024-06-01 18:57 UTC, closed without merging