Fix(black): formatting excluded files results in blank buffer (#249)
stevearc/conform.nvim pull request #254
Opened 2023-12-27 01:35 UTC by bartels

Fixes #249 

This fix checks for blank formatter output in `apply_format`. Not sure if this is the best place to apply this fix, but seemed  the most obvious place since it'll work the same for both sync and async formats

2023-12-28 02:50 UTC, stevearc requested changes
Approach looks good, but the fuzz tester is failing. You may need to adjust the fuzz tester to not trigger this condition

2023-12-28 02:50 UTC, stevearc commented on lua/conform/runner.lua
> +  end
I think this is a fine place for it, but I'd say add the buffer name to the log line and make it a `warn` instead of a `trace`

2023-12-28 02:50 UTC, stevearc commented on tests/runner_spec.lua
> +      test_util.set_formatter_output({ "" })
I recently made a change the moved this out of `test_util`. You may need to rework the test a bit.

2024-01-02 16:26 UTC, merged

2024-01-02 16:26 UTC, stevearc commented
Thanks for the PR!

2024-01-03 13:51 UTC, Mange commented
Thanks! This helped me with the `rubocop` formatter that also started clearing all my files on format for no discernible reason after updating 2 days ago.

I'll try to figure out why *that* happens and report it later on, but now I can get back to work. :heart: