feat(formatters): add nixfmt-rfc-style
stevearc/conform.nvim pull request #505
Opened 2024-07-30 14:10 UTC by ugur-a

This is different from `nixfmt`, which is currently defined at:
https://github.com/stevearc/conform.nvim/blob/25d48271e3d4404ba017cb92a37d3a681c1ad149/lua/conform/formatters/nixfmt.lua

This new formatter is meant to eventually replace `nixfmt`. More information can be found on [their repo](https://github.com/NixOS/nixfmt)

2024-07-30 14:17 UTC, ugur-a commented
On another thought, the same command is used by both versions, so maybe just:
- update the repo link - the current one (https://github.com/serokell/nixfmt) already redirects to the new one (https://github.com/NixOS/nixfmt) 
- update the description - it seems to come from the old repo, which, as I said, doesn't seem to be there anymore

This way, `conform.nvim` will just use the version that's currenty installed

2024-08-07 05:24 UTC, stevearc requested changes
I agree, updating the repo + description of the existing formatter sounds like the correct move here

2024-08-07 07:21 UTC, ugur-a commented
Done!

2024-08-07 16:02 UTC, stevearc commented
Thanks for the PR!

2024-08-07 16:03 UTC, merged