feat(php-cs-fixer): Add support for php-cs-fixer
stevearc/conform.nvim pull request #78
Opened 2023-09-26 06:56 UTC by aidenlangley

- Added a simple utility to check a list of paths and return the first that exists, or a default. Useful for defining commands for a formatter so it will call the correct executable.
- Added support for `php-cs-fixer`.

2023-09-26 17:20 UTC, stevearc requested changes

2023-09-26 17:20 UTC, stevearc commented on lua/conform/util.lua
> +
There are some subtle edge cases here surrounding when these paths get resolved and cwd vs tab cwd vs window cwd. I've added a utility function that handles those cases called `find_executable` that takes the same parameters. If you rebase from latest master you can use that instead

2023-09-26 23:00 UTC, aidenlangley commented
Using `find_executable` now instead. Hope the history isn't too messy.

2023-09-27 03:42 UTC, stevearc commented
Thanks for the PR!

2023-09-27 03:42 UTC, merged